title = "noscript"
author = "135e2"
difficulty = "Easy"
flag = "susctf{n0_scr1p7_4_0Id_5cho0l3rs_[TEAM_HASH]}"

description = """
... in the good-old C we trust.

åˆ«çœ‹äº†ï¼Œä¸æ˜¯è®©ä½ åš pwn çš„ ğŸ˜¡
"""

[attachments]
path = "build/**"

[container]
port = 8080
memory = "64" # unit: MiB
storage = "640" # unit: MiB
